// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM3kQcDo9sLNVRm4GtUtBAIbfoU_BpjUk',
    appId: '1:503081136683:web:7f9d368eec0521f6d2f06e',
    messagingSenderId: '503081136683',
    projectId: 'siksa-ba971',
    authDomain: 'siksa-ba971.firebaseapp.com',
    storageBucket: 'siksa-ba971.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCciJMTLJVCCFSRyZpRfO0rbPajXBJeJUs',
    appId: '1:503081136683:android:507748f6045c65b3d2f06e',
    messagingSenderId: '503081136683',
    projectId: 'siksa-ba971',
    storageBucket: 'siksa-ba971.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH3r1EkhXUICQvka6KWOtHgocDL7_UqM8',
    appId: '1:503081136683:ios:6245e3ebb84b8406d2f06e',
    messagingSenderId: '503081136683',
    projectId: 'siksa-ba971',
    storageBucket: 'siksa-ba971.firebasestorage.app',
    iosClientId: '503081136683-cjkjltanmrsd4t4dntv67i7cpoficj84.apps.googleusercontent.com',
    iosBundleId: 'com.hongnyhengchin.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH3r1EkhXUICQvka6KWOtHgocDL7_UqM8',
    appId: '1:503081136683:ios:df0669619e98c9fed2f06e',
    messagingSenderId: '503081136683',
    projectId: 'siksa-ba971',
    storageBucket: 'siksa-ba971.firebasestorage.app',
    iosClientId: '503081136683-t42gvju3squup3neusi3a6dra377eq1f.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM3kQcDo9sLNVRm4GtUtBAIbfoU_BpjUk',
    appId: '1:503081136683:web:b917bf9bd7564e17d2f06e',
    messagingSenderId: '503081136683',
    projectId: 'siksa-ba971',
    authDomain: 'siksa-ba971.firebaseapp.com',
    storageBucket: 'siksa-ba971.firebasestorage.app',
  );
}
